name: Image Compresser
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: read
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Commit and push if changes
        env:
          GIT_USERNAME: Tanmay000009
          GIT_EMAIL: Tanmay000009-action@github.com
          DEPLOY_URL: github.com/Tanmay000009/actions_test
        run: |-
          git diff
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/Tanmay000009/actions_test
          git config --local user.name "${{ env.GIT_USERNAME }}"
          git config --local user.email "${{ env.GIT_EMAIL }}"
          git add .
          git commit -m "Image optimized"
          git push "https://${{ env.GIT_USERNAME }}:${{ secrets.GITHUB_TOKEN }}@${{ env.DEPLOY_URL }}" master:master