name: Image Compresser
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: read
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Commit and push if changes
        run: |-
          git diff
          git config --local user.email "tanmayvyas009@gmail.com"
          git config --local user.name "Tanmay"
          git add .
          git commit -m "Image optimized"
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push